language: go
go:
- '1.8'
before_install:
- go get github.com/mitchellh/gox
install:
- true
script:
- go test -v
after_success:
- "./build.sh"
deploy:
  provider: releases
  api_key:
    secure: maTmrRi06lUn/DXti2D14W20SbGEZZJVLJRpkxHs4ieMvneAaQpDGWBy3glnp8nQNTPRiMgsHRID6N0dBzHsvjWW+XvS226Lbw7XOvgb5z/VD0e50GAyPVPBV/qRsYTGiNZatvZwGoW+B8hGS47qxVcMg9k6wWW5uMJtCafRFt7rpQdiAt+HN2Sw82xPVkcVBkEQi+G+8HOQG+qVUX69Of9bQNb0P09BfeSl/1YwHb1H3b0/vbQZksG2cQBLagn1M/a94wvFWWy459Rap2BNe+arnhx6haI7sqfpL/iyliACge3mXwcgLU9VJuKPjhBnGesBWocFP6wVzRGoHQTKkNF39AaBKHCdUgymKIGi8j6at9xQvtNcwaXEUnNNLmI29xOb7+GKuX/esqMMU9/hY8xt2HgyI1lk5UIzFzONDf8VoPl6RUl8VuWLRX+RYE2B/aD+/XEHOP6jMD8vlOil3Fzv+f2CBKZUM1s+C1nwlh7HUAYmtiOuUl7lpXqrlowAfV+Wm20RojAVYhY7ClmcVLWa4uOYWzXVj7y2Mrq/aBBMJm05qHURsDLPSrQDmXbQjmKkzRA9VGYBS8ScdGNkFEnjuzKWjSj3bklCG4x3fBRdZntFveHgzTXD8HzcX0teXbdT2kAnU3gVL7CKJKQawWXCL4u7CFczcD7COLzRRKw=
  skip_cleanup: true
  file_glob: true
  file: dist/*
  on:
    tags: true
    repo: zenreach/ec2-env
